apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devopszon-httpapi-host
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devopszon
  source:
    repoURL: https://github.com/devopszon/devopszon-dev-devopszon-httpapi-host-3a1d864e-526b-0f33-2db3-9fbaad258b59.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: devopszon
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true