apiVersion: v1
kind: Service
metadata:
  name: devopszon-httpapi-host
  namespace: devopszon
  labels:
    app: devopszon-httpapi-host
    service: devopszon-httpapi-host
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    service: devopszon-httpapi-host
  